apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-java-app
  labels:
    app: docker-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-java-app
  template:
    metadata:
      labels:
        app: docker-java-app
    spec:
      containers:
      - name: docker-java-app
        image: riteshmishra26/docker-java-app:app   # Jenkins pipeline push karega
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/gcp-key.json
        volumeMounts:
        - name: gcp-key-volume
          mountPath: /app/gcp-key.json
          subPath: gcp-key.json
      volumes:
      - name: gcp-key-volume
        secret:
          secretName: gcp-key   # Kubernetes secret me tumhara GCP JSON hoga
